CREATE TABLE [dbo].[Events]
(
    [Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Type] NVARCHAR(100) NOT NULL,
    [User] NVARCHAR(100) NOT NULL,
    [Channel] NVARCHAR(100) NOT NULL,
    [Text] NVARCHAR(MAX) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [UpdatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
) 