CREATE TABLE [dbo].[Events]
(
    [Id] INT IDENTITY(1,1) NOT NULL,
    [Type] NVARCHAR(100) NOT NULL,
    [User] NVARCHAR(100) NOT NULL,
    [Channel] NVARCHAR(100) NOT NULL,
    [Text] NVARCHAR(1000) NOT NULL,
    [CreatedAt] DATETIME NOT NULL,
    [UpdatedAt] DATETIME NOT NULL,
    CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED 
    (
        [Id] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
